/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Data;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-09-02T08:13:50.931Z")

@Api(value = "res", description = "the res API")
@RequestMapping(value = "")
public interface ResApi {

    @ApiOperation(value = "&quot;bag&quot;", nickname = "resPut", notes = "", response = Object.class, tags={ "默认分组", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "success", response = Object.class) })
    @RequestMapping(value = "/res",
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Object> resPut(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Data data);

}
